connection:
    host: 'https://stage.vivaconagua.org'
mysql:
    host: 172.2.1.10
    user: root
    passwd: 'yes'
    database: db175370026
drops:
    email: t.kaestle@vivaconagua.org
    password: k9gtAffe!vca3586
