connection:
    host: 'https://stage.vivaconagua.org'
mysql:
    host: 172.2.1.10
    user: root
    passwd: 
    database: db175370026
stream:
    host: 172.2.200.2
    user: stream
    passwd:
    database: stream
drops:
    email: 
    password: 
